import torch
import torch.nn.functional as F
import numpy as np
import logging
import json

from radiance.core.tensor.chunking import chunks, compute_device, frames_per_chunk

logger = logging.getLogger("radiance.vfx.masking")

_SAM_NOT_SHIPPED = (
    "Radiance does not ship a SAM runtime in 3.5.0. The SAM Loader and SAM "
    "Mask Generator are placeholders kept only so saved graphs still open; "
    "they never ran a segmentation model. Use a SAM2 node pack (for example "
    "ComfyUI-segment-anything-2) and feed its MASK into Radiance."
)


class RadianceSAMModelLoader:
    """
    ◎ Radiance SAM Model Loader (not shipped in 3.5.0)

    Hidden from the node menu. Saved graphs load; executing raises a clear
    error because no SAM runtime is bundled. See KNOWN_ISSUES.md.
    """

    DEPRECATED = True
    
    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "model_name": ("STRING", {"default": "", "tooltip": "Not used: no SAM runtime ships with Radiance 3.5.0."}),
                "device": (["cuda", "cpu", "mps"], {"default": "cuda"}),
                "offload_to_cpu": ("BOOLEAN", {"default": False}),
                "dtype": (["float16", "bfloat16", "float32"], {"default": "float16"}),
            }
        }

    RETURN_TYPES = ("SAM_MODEL",)
    RETURN_NAMES = ("sam_model",)
    FUNCTION = "load"
    CATEGORY = "FXTD STUDIOS/Radiance/◎ VFX/Masking"

    def load(self, model_name: str = "", device: str = "cuda", offload_to_cpu: bool = False, dtype: str = "float16"):
        raise RuntimeError(f"[SAM Loader] {_SAM_NOT_SHIPPED}")


class RadianceSAMGenerator:
    """
    ◎ Radiance SAM Mask Generator (not shipped in 3.5.0)

    Hidden from the node menu. The previous body drew fixed-radius discs
    around the points and thresholded colour words; it was not SAM.
    Executing now raises a clear error. See KNOWN_ISSUES.md.
    """

    DEPRECATED = True
    
    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "image": ("IMAGE",),
                "sam_model": ("SAM_MODEL",),
                "points": ("STRING", {"default": "[[256, 256]]", "multiline": True}),
                "point_labels": ("STRING", {"default": "[1]", "multiline": False}),
            },
            "optional": {
                "text_prompt": ("STRING", {"default": ""}),
                "bbox": ("STRING", {"default": ""}),
            }
        }

    RETURN_TYPES = ("MASK", "IMAGE")
    RETURN_NAMES = ("mask", "masked_image")
    FUNCTION = "generate"
    CATEGORY = "FXTD STUDIOS/Radiance/◎ VFX/Masking"

    def generate(self, image=None, sam_model=None, points="", point_labels="", text_prompt: str = "", bbox: str = ""):
        raise RuntimeError(f"[SAM Generator] {_SAM_NOT_SHIPPED}")


class RadianceMultiMaskVisualPicker:
    """
    ◎ Radiance Multi-Mask Picker
    
    Exposes an interactive selector to pick between multiple candidate masks
    generated by segmenters. Can be configured dynamically or via a fallback picker index.
    """
    
    DESCRIPTION = "Pick one mask from a stack of candidate masks (for example the several outputs of a segmenter) by index."

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "masks": ("MASK", {"tooltip": "Candidate masks. A standard MASK batch (N, H, W) is treated as N candidates for one frame; a 4-D (B, N, H, W) stack picks the same candidate on every frame."}),
                "picker_index": ("INT", {"default": 0, "min": 0, "max": 5, "step": 1, "tooltip": "Zero-based index of the candidate to output. Wraps around if it is past the number of candidates."}),
            }
        }

    RETURN_TYPES = ("MASK",)
    RETURN_NAMES = ("selected_mask",)
    FUNCTION = "pick"
    CATEGORY = "FXTD STUDIOS/Radiance/◎ VFX/Masking"

    def pick(self, masks: torch.Tensor, picker_index: int):
        # masks can be shape [N, H, W] or [B, N, H, W]
        if masks.dim() == 3:
            # Multi-candidate single frame
            N, H, W = masks.shape
            selected = picker_index % N
            output = masks[selected].unsqueeze(0)
        elif masks.dim() == 4:
            # Batch of candidate masks
            B, N, H, W = masks.shape
            selected = picker_index % N
            output = masks[:, selected]
        else:
            output = masks
            
        logger.info(f"[Multi-Mask Picker] Visual pick resolved to mask index: {picker_index}")
        return (output,)


class RadianceLinearMatting:
    """
    ◎ Radiance Linear Alpha Matting
    
    Refines a rough mask into a soft alpha with a guided filter run on the
    scene-linear image (no learned matting model). Earlier builds listed
    ViTMatte and RVM; neither was ever implemented, both ran this filter.
    """

    DESCRIPTION = "Refine a rough mask into a soft alpha matte with a guided filter that follows the image's edges (no learned matting model). Also outputs the image premultiplied by the matte."

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "image": ("IMAGE", {"tooltip": "Guide image whose edges the matte will follow. Used as given (scene-linear or display-encoded); eps behaves differently for each."}),
                "mask": ("MASK", {"tooltip": "Rough matte to refine, 0 to 1."}),
                "method": (["GuidedFilter"], {"default": "GuidedFilter", "tooltip": "Guided filter on the scene-linear image. The only method implemented."}),
                "trimap_dilation": ("INT", {"default": 12, "min": 0, "max": 128, "step": 1, "tooltip": "Guided filter radius in pixels (window 2 x radius + 1). No trimap is built despite the name; larger values refine a wider band around edges and soften more. 0 = no filtering."}),
                "eps": ("FLOAT", {"default": 1e-4, "min": 1e-6, "max": 1e-1, "step": 1e-6, "tooltip": "Guided filter regularisation. Small values make the matte follow fine image edges closely; large values give a smoother matte closer to a blurred mask."}),
            }
        }

    RETURN_TYPES = ("MASK", "IMAGE")
    RETURN_NAMES = ("alpha_matte", "foreground_image")
    FUNCTION = "apply"
    CATEGORY = "FXTD STUDIOS/Radiance/◎ VFX/Masking"

    def apply(self, image: torch.Tensor, mask: torch.Tensor, method: str, trimap_dilation: int, eps: float):
        B, H, W, C = image.shape
        if mask.dim() == 2:
            mask = mask.unsqueeze(0)
        if tuple(mask.shape[-2:]) != (H, W):
            # ComfyUI's Load Image returns a 64x64 mask for an image with no
            # alpha; any other size mismatch crashed here too.
            mask = F.interpolate(mask.float().unsqueeze(1), size=(H, W), mode="bilinear",
                                 align_corners=False).squeeze(1)
        # Guided filter (He et al.) on the image as given:
        #   a = cov(I, p) / (var(I) + eps),  b = mean(p) - a * mean(I),
        #   q = mean(a) * I + mean(b), averaged over channels.
        r = trimap_dilation * 2 + 1
        pad = r // 2

        def box(x):
            # 3.5.0: the r x r zero-padded mean as two 1-D passes. Identical
            # result (zero padding, divisor r*r), O(r) instead of O(r^2) per
            # pixel. The 2-D pool took 4.5 s a frame at 1024x576 with the
            # default radius.
            if r == 1:
                return x
            x = F.avg_pool2d(x, (1, r), stride=1, padding=(0, pad))
            return F.avg_pool2d(x, (r, 1), stride=1, padding=(pad, 0))

        dev = compute_device()
        alpha = torch.empty((B, H, W), dtype=torch.float32)
        foreground = torch.empty((B, H, W, C), dtype=torch.float32)
        # Frames per chunk: about 12 frame-sized buffers are alive at once.
        per = frames_per_chunk(H, W, C, 12.0, dev)
        single_mask = mask.shape[0] == 1
        for a0, a1 in chunks(B, per):
            I = image[a0:a1].to(dev, torch.float32).permute(0, 3, 1, 2)
            p = (mask[:1] if single_mask else mask[a0:a1]).to(dev, torch.float32).unsqueeze(1)
            mean_I = box(I)
            mean_p = box(p)
            cov_Ip = box(I * p) - mean_I * mean_p
            var_I = box(I * I) - mean_I * mean_I
            a = cov_Ip / (var_I + eps)
            b = mean_p - a * mean_I
            del cov_Ip, var_I
            q = (box(a) * I + box(b)).mean(dim=1, keepdim=True).clamp_(0.0, 1.0)
            alpha[a0:a1] = q.squeeze(1).cpu()
            foreground[a0:a1] = (I * q).permute(0, 2, 3, 1).cpu()
            del I, p, mean_I, mean_p, a, b, q

        logger.info(f"[Linear Matting] Guided filter, radius {pad}, eps {eps}")
        return (alpha, foreground)
