import torch
import torch.nn.functional as F
import numpy as np
import logging
import json

logger = logging.getLogger("radiance.vfx.masking")

_SAM_NOT_SHIPPED = (
    "Radiance does not ship a SAM runtime in 3.5.0. The SAM Loader and SAM "
    "Mask Generator are placeholders kept only so saved graphs still open; "
    "they never ran a segmentation model. Use a SAM2 node pack (for example "
    "ComfyUI-segment-anything-2) and feed its MASK into Radiance."
)


class RadianceSAMModelLoader:
    """
    ◎ Radiance SAM Model Loader (not shipped in 3.5.0)

    Hidden from the node menu. Saved graphs load; executing raises a clear
    error because no SAM runtime is bundled. See KNOWN_ISSUES.md.
    """

    DEPRECATED = True
    
    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "model_name": ("STRING", {"default": "", "tooltip": "Not used: no SAM runtime ships with Radiance 3.5.0."}),
                "device": (["cuda", "cpu", "mps"], {"default": "cuda"}),
                "offload_to_cpu": ("BOOLEAN", {"default": False}),
                "dtype": (["float16", "bfloat16", "float32"], {"default": "float16"}),
            }
        }

    RETURN_TYPES = ("SAM_MODEL",)
    RETURN_NAMES = ("sam_model",)
    FUNCTION = "load"
    CATEGORY = "FXTD STUDIOS/Radiance/◎ VFX/Masking"

    def load(self, model_name: str = "", device: str = "cuda", offload_to_cpu: bool = False, dtype: str = "float16"):
        raise RuntimeError(f"[SAM Loader] {_SAM_NOT_SHIPPED}")


class RadianceSAMGenerator:
    """
    ◎ Radiance SAM Mask Generator (not shipped in 3.5.0)

    Hidden from the node menu. The previous body drew fixed-radius discs
    around the points and thresholded colour words; it was not SAM.
    Executing now raises a clear error. See KNOWN_ISSUES.md.
    """

    DEPRECATED = True
    
    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "image": ("IMAGE",),
                "sam_model": ("SAM_MODEL",),
                "points": ("STRING", {"default": "[[256, 256]]", "multiline": True}),
                "point_labels": ("STRING", {"default": "[1]", "multiline": False}),
            },
            "optional": {
                "text_prompt": ("STRING", {"default": ""}),
                "bbox": ("STRING", {"default": ""}),
            }
        }

    RETURN_TYPES = ("MASK", "IMAGE")
    RETURN_NAMES = ("mask", "masked_image")
    FUNCTION = "generate"
    CATEGORY = "FXTD STUDIOS/Radiance/◎ VFX/Masking"

    def generate(self, image=None, sam_model=None, points="", point_labels="", text_prompt: str = "", bbox: str = ""):
        raise RuntimeError(f"[SAM Generator] {_SAM_NOT_SHIPPED}")


class RadianceMultiMaskVisualPicker:
    """
    ◎ Radiance Multi-Mask Picker
    
    Exposes an interactive selector to pick between multiple candidate masks
    generated by segmenters. Can be configured dynamically or via a fallback picker index.
    """
    
    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "masks": ("MASK",),
                "picker_index": ("INT", {"default": 0, "min": 0, "max": 5, "step": 1}),
            }
        }

    RETURN_TYPES = ("MASK",)
    RETURN_NAMES = ("selected_mask",)
    FUNCTION = "pick"
    CATEGORY = "FXTD STUDIOS/Radiance/◎ VFX/Masking"

    def pick(self, masks: torch.Tensor, picker_index: int):
        # masks can be shape [N, H, W] or [B, N, H, W]
        if masks.dim() == 3:
            # Multi-candidate single frame
            N, H, W = masks.shape
            selected = picker_index % N
            output = masks[selected].unsqueeze(0)
        elif masks.dim() == 4:
            # Batch of candidate masks
            B, N, H, W = masks.shape
            selected = picker_index % N
            output = masks[:, selected]
        else:
            output = masks
            
        logger.info(f"[Multi-Mask Picker] Visual pick resolved to mask index: {picker_index}")
        return (output,)


class RadianceLinearMatting:
    """
    ◎ Radiance Linear Alpha Matting
    
    Refines a rough mask into a soft alpha with a guided filter run on the
    scene-linear image (no learned matting model). Earlier builds listed
    ViTMatte and RVM; neither was ever implemented, both ran this filter.
    """
    
    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "image": ("IMAGE",),
                "mask": ("MASK",),
                "method": (["GuidedFilter"], {"default": "GuidedFilter", "tooltip": "Guided filter on the scene-linear image. The only method implemented."}),
                "trimap_dilation": ("INT", {"default": 12, "min": 0, "max": 128, "step": 1}),
                "eps": ("FLOAT", {"default": 1e-4, "min": 1e-6, "max": 1e-1, "step": 1e-6}),
            }
        }

    RETURN_TYPES = ("MASK", "IMAGE")
    RETURN_NAMES = ("alpha_matte", "foreground_image")
    FUNCTION = "apply"
    CATEGORY = "FXTD STUDIOS/Radiance/◎ VFX/Masking"

    def apply(self, image: torch.Tensor, mask: torch.Tensor, method: str, trimap_dilation: int, eps: float):
        # Ensure correct shapes
        B, H, W, C = image.shape
        
        # Bring mask to [B, 1, H, W]
        if mask.dim() == 3:
            mask_bchw = mask.unsqueeze(1)
        else:
            mask_bchw = mask
            
        # Bilateral / Guided Filter implementation in scene-linear Torch space
        # Operating in scene-linear avoids sub-pixel edge fringing because sRGB curve doesn't warp color profiles.
        img_bchw = image.permute(0, 3, 1, 2)
        
        # Compute local means
        # Kernel size derived from dilation
        r = trimap_dilation * 2 + 1
        
        # Guided Filter Math in pure Torch
        # q = a * I + b
        # a = (cov(I, p)) / (var(I) + eps)
        # b = mean(p) - a * mean(I)
        
        # Pad inputs
        pad = r // 2
        I = img_bchw
        p = mask_bchw
        
        mean_I = F.avg_pool2d(I, r, stride=1, padding=pad)
        mean_p = F.avg_pool2d(p, r, stride=1, padding=pad)
        mean_Ip = F.avg_pool2d(I * p, r, stride=1, padding=pad)
        
        cov_Ip = mean_Ip - mean_I * mean_p
        
        mean_II = F.avg_pool2d(I * I, r, stride=1, padding=pad)
        var_I = mean_II - mean_I * mean_I
        
        a = cov_Ip / (var_I + eps)
        b = mean_p - a * mean_I
        
        mean_a = F.avg_pool2d(a, r, stride=1, padding=pad)
        mean_b = F.avg_pool2d(b, r, stride=1, padding=pad)
        
        q = mean_a * I + mean_b
        q = q.mean(dim=1, keepdim=True)
        q = q.clamp(0.0, 1.0)
        
        # Output alpha matte as [B, H, W]
        alpha = q.squeeze(1)
        foreground = image * q.permute(0, 2, 3, 1)
        
        logger.info(f"[Linear Matting] Guided filter, radius {r // 2}, eps {eps}")
        return (alpha, foreground)
